# Generated by Django 4.2.6 on 2024-01-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert', models.TextField(verbose_name='LABEL_ALERT')),
                ('status', models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'REMOVED')], default=1, verbose_name='LABEL_STATUS')),
            ],
            options={
                'verbose_name': 'MODEL_NAME_SITEALERT',
                'verbose_name_plural': 'MODEL_NAME_SITEALERT_PLURAL',
            },
        ),
    ]
