# Generated by Django 4.2.4 on 2023-12-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0048_alter_revealrule_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback_json',
            field=models.JSONField(blank=True, null=True, verbose_name='LABEL_FEEDBACK_JSON'),
        ),
    ]
